sudo: false

language: php

php:
  # - '7.1'
  - '7.2'
  # - nightly

env:
  # - WP_VERSION=4.9.4 WP_MULTISITE=0
  # - WP_VERSION=4.9.4 WP_MULTISITE=1
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

matrix:
  allow_failures:
    - php: nightly

install: composer install

before_script:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - vendor/bin/psalm
  - vendor/bin/phpunit

addons:
  # Install MariaDB version which supports JSON
  mariadb: '10.2'
